"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const body_parser_1 = __importDefault(require("body-parser"));
const cors_1 = __importDefault(require("cors"));
const index_js_1 = require("./routes/index.js");
const viewJobs_js_1 = require("./routes/viewJobs.js");
const viewProduction_js_1 = require("./routes/viewProduction.js");
const inputProduction_js_1 = require("./routes/inputProduction.js");
const inputDataPOST_js_1 = require("./routes/inputDataPOST.js");
const deleteDataPOST_js_1 = require("./routes/deleteDataPOST.js");
const editDataPOST_js_1 = require("./routes/editDataPOST.js");
const viewTickets_js_1 = require("./routes/viewTickets.js");
const adminPage_js_1 = require("./routes/adminPage.js");
const alterJobsPOST_js_1 = require("./routes/alterJobsPOST.js");
const refreshTicketsPOST_js_1 = require("./routes/refreshTicketsPOST.js");
const updateJobResponsesPOST_js_1 = require("./routes/updateJobResponsesPOST.js");
const asBuilts_js_1 = require("./routes/asBuilts.js");
const generatePdfPOST_js_1 = require("./routes/generatePdfPOST.js");
const maintenance_js_1 = require("./routes/maintenance.js");
const app = (0, express_1.default)();
const PORT = 3000;
app.locals.basedir = "/";
app.set('view engine', 'pug');
app.set('views', `${process.cwd()}/views`);
app.use(express_1.default.static('public'));
app.use(body_parser_1.default.json());
app.use((0, cors_1.default)());
app.use('/', index_js_1.router);
app.use('/viewJobs', viewJobs_js_1.router);
app.use('/inputProduction', inputProduction_js_1.router);
app.use('/viewProduction', viewProduction_js_1.router);
app.use('/inputData', inputDataPOST_js_1.router);
app.use('/deleteData', deleteDataPOST_js_1.router);
app.use('/editData', editDataPOST_js_1.router);
app.use('/viewTickets', viewTickets_js_1.router);
app.use('/admin', adminPage_js_1.router);
app.use('/alterJobs', alterJobsPOST_js_1.router);
app.use('/refreshTickets', refreshTicketsPOST_js_1.router);
app.use('/updateJobResponses', updateJobResponsesPOST_js_1.router);
app.use('/asBuilts', asBuilts_js_1.router);
app.use('/generatePDF', generatePdfPOST_js_1.router);
app.use('/maintenance', maintenance_js_1.router);
app.listen(PORT, () => {
    console.log(`listening @ http://192.168.1.247:3000`);
});
